import os
from typing import Any, Dict

from src.core.agent import GitHubClientWrapper
from src.core.config import get_settings
from src.core.state_manager import TaskState


async def completion_node(
    state: TaskState, workflows: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Phase 5: Completion (完了報告)
    """
    if "completion" not in workflows:
        print("Error: Completion workflow is missing.")
        return {
            "status": "Completed",
            "history": [{"node": "completion", "status": "no_workflow_fallback"}],
        }

    gh = GitHubClientWrapper(os.getenv("GITHUB_TOKEN", ""))
    repo_name = state["task_id"].split("#")[0]
    issue_number = int(state["task_id"].split("#")[1])

    has_changes = state.get("has_changes", False)
    topic_branch = state.get("topic_branch")

    completion_wf = workflows["completion"]

    try:
        # Pydantic-AI ワークフローを実行し、修正サマリーと PR 本文を生成
        # 入力にはこれまでの実行サマリーなどを渡す
        input_summary = state.get("execution_result_summary", "No summary available.")
        wf_result = await completion_wf(input_data=input_summary)
        results = wf_result.get("results", {})

        summ = results.get("execution_result_summary", input_summary)
        pr_title = results.get("pr_title", f"Fix for {state['task_id']}")
        pr_body = results.get("pr_body", "PR generated by Brownie.")

        if has_changes and topic_branch:
            # PR 作成
            pr = await gh.create_pull_request(
                repo_name, pr_title, pr_body, topic_branch, "main"
            )
            pr_url = pr.html_url if pr else "Failed to get PR URL"

            msg = f"✅ PR を作成しました: {pr_url}\n承認ありがとうございました。"
            await gh.post_comment(repo_name, issue_number, msg + get_settings().footer)

            return {
                "status": "Completed",
                "pr_url": pr_url,
                "execution_result_summary": summ,
                "history": [{"node": "completion", "status": "pr_created"}],
            }
        else:
            msg = "✅ タスクを完了しました（コード修正は不要と判断されました）。\n承認ありがとうございました。"
            await gh.post_comment(repo_name, issue_number, msg + get_settings().footer)
            return {
                "status": "Completed",
                "history": [{"node": "completion", "status": "no_changes"}],
            }

    except Exception as e:
        print(f"Completion failed: {e}")
        return {
            "status": "Failed",
            "metadata": {"error": str(e)},
            "history": [{"node": "completion", "status": "failed"}],
        }
