# tests/test_core/test_orchestrator.py
import pytest
import json
import httpx
from pathlib import Path
from unittest.mock import patch, MagicMock, AsyncMock
from core.orchestrator import Orchestrator, Settings, GatewayClient
from core.events import TextDeltaEvent, ToolCallStartEvent, ToolCallDeltaEvent, SystemToolCallEvent, WorkflowFinishEvent, ErrorEvent
from core.schema import InternalAgentRequest, InternalMessage, InternalTool
from core.llm_client import StandardLLMChunk, ToolCallChunk
import mcp.types as types

@pytest.fixture
def mock_gateway():
    with patch("core.orchestrator.GatewayClient") as mock:
        inst = mock.return_value
        inst.start = AsyncMock()
        inst.stop = AsyncMock()
        inst.fetch_tools = AsyncMock(return_value=[{"name": "test_tool", "description": "desc", "inputSchema": {}}])
        inst.call_tool = AsyncMock(return_value="Success")
        yield inst

@pytest.fixture
def orchestrator(mock_gateway):
    with patch("pathlib.Path.exists", return_value=False):
        o = Orchestrator("dummy.yaml")
        # テストのためにダミーの mlx-launcher クライアントを注入する
        o.mcp_clients["mlx-launcher"] = mock_gateway
        return o

@pytest.mark.asyncio
async def test_start_shutdown(orchestrator, mock_gateway):
    # Auto-launch のテストのために設定を注入
    orchestrator.settings.llm.models = {"interlocutor": "dummy-model"}
    orchestrator.settings.llm.launcher_client = "mlx-launcher"
    orchestrator.settings.llm.launcher_tool = "launch_llm_server"

    await orchestrator.start()
    
    assert mock_gateway.start.call_count >= 1
    mock_gateway.call_tool.assert_called_with("launch_llm_server", {"model_name": "dummy-model", "port": 8080})
    
    await orchestrator.shutdown()
    assert mock_gateway.stop.call_count >= 1

@pytest.mark.asyncio
async def test_run_workflow_interlocutor(orchestrator):
    async def mock_stream_chat(*args, **kwargs):
        yield StandardLLMChunk(content="Hello")
        yield StandardLLMChunk(finish_reason="stop")
        
    orchestrator.llm_client.stream_chat = mock_stream_chat

    req = InternalAgentRequest(messages=[InternalMessage(role="user", content="Hi")])
    events = [e async for e in orchestrator.process_workflow(req)]
    
    assert len(events) == 2
    assert isinstance(events[0], TextDeltaEvent)
    assert events[0].content == "Hello"
    assert isinstance(events[1], WorkflowFinishEvent)
    assert events[1].finish_reason == "stop"

@pytest.mark.asyncio
async def test_run_workflow_with_reflection(orchestrator):
    """Restored: Test reflection (reranking) when no tool call is generated by LLM."""
    
    async def mock_stream_chat(*args, **kwargs):
        yield StandardLLMChunk(content="Hello World")
        yield StandardLLMChunk(finish_reason="stop")
        
    orchestrator.llm_client.stream_chat = mock_stream_chat
    orchestrator._extract_intent = AsyncMock(return_value="Conclude task")
    
    # Reranker モックの準備
    mock_reranker = AsyncMock()
    mock_reranker.call_tool.return_value = json.dumps([{"document": "Concludes the interaction", "score": 0.99}])
    orchestrator.mcp_clients["mcp-reranker"] = mock_reranker

    req = InternalAgentRequest(
        messages=[InternalMessage(role="user", content="Hi")],
        tools=[InternalTool(
            type="function",
            function={
                "name": "custom_finish_tool",
                "description": "Concludes the interaction",
                "parameters": {
                    "properties": {"summary": {"type": "string"}, "is_done": {"type": "boolean"}},
                    "required": ["summary", "is_done"]
                }
            }
        )]
    )

    events = [e async for e in orchestrator.process_workflow(req)]
    
    # TextDelta + SystemToolCall + WorkflowFinish
    assert any(isinstance(e, SystemToolCallEvent) and e.tool_name == "custom_finish_tool" for e in events)
    assert any(isinstance(e, WorkflowFinishEvent) for e in events)

@pytest.mark.asyncio
async def test_workflow_missing_model_key(orchestrator):
    req = InternalAgentRequest(messages=[InternalMessage(role="user", content="Fix bug")])
    events = [e async for e in orchestrator._raw_run_workflow("interlocutor", req, workflow_steps=[{"type": "llm_chat"}])]
    
    assert len(events) == 1
    assert isinstance(events[0], ErrorEvent)

@pytest.mark.asyncio
async def test_call_llm_stream_fallback_rewrite(orchestrator):
    async def mock_stream_chat(*args, **kwargs):
        yield StandardLLMChunk(
            tool_calls=[ToolCallChunk(index=0, id="call_1", name="hallucinated_tool")]
        )
        yield StandardLLMChunk(
            tool_calls=[ToolCallChunk(index=0, arguments='{"text": "Sure!"}')],
            finish_reason="tool_calls"
        )
        
    orchestrator.llm_client.stream_chat = mock_stream_chat
    
    req = InternalAgentRequest(
        messages=[InternalMessage(role="user", content="Hi")],
        tools=[InternalTool(
            type="function",
            function={
                "name": "valid_client_tool",
                "parameters": {"properties": {"msg": {"type": "string"}}, "required": ["msg"]}
            }
        )]
    )

    events = [e async for e in orchestrator._call_llm("interlocutor", "http://dummy", req)]
    
    assert any(isinstance(e, SystemToolCallEvent) and e.tool_name == "valid_client_tool" for e in events)

@pytest.mark.asyncio
async def test_stream_llm_timeout_user_prompt(orchestrator):
    """Test that _raw_stream_llm catches TimeoutException and yields a user prompt."""
    async def mock_stream_chat_timeout(*args, **kwargs):
        yield StandardLLMChunk(content="Thinking...")
        raise httpx.TimeoutException("Stream timed out")

    orchestrator.llm_client.stream_chat = mock_stream_chat_timeout
    req = InternalAgentRequest(messages=[InternalMessage(role="user", content="Hi")])
    
    events = [e async for e in orchestrator._raw_stream_llm("interlocutor", "http://dummy", req)]
    
    # タイムアウト時にクラッシュせず、テキストメッセージとlengthフィニッシュを出力するか確認
    assert len(events) == 3
    assert isinstance(events[0], TextDeltaEvent)
    assert events[0].content == "Thinking..."
    assert isinstance(events[1], TextDeltaEvent)
    assert "システム通知" in events[1].content
    assert isinstance(events[2], WorkflowFinishEvent)
    assert events[2].finish_reason == "length"

@pytest.mark.asyncio
async def test_extract_intent_timeout_fallback(orchestrator):
    """Test that _extract_intent handles timeouts gracefully and returns 'Unknown intent'."""
    with patch.object(orchestrator.http_client, "post", new_callable=AsyncMock) as mock_post:
        mock_post.side_effect = httpx.TimeoutException("Timeout occurred")
        
        intent = await orchestrator._extract_intent("Some long text...")
        assert intent == "Unknown intent"
        mock_post.assert_called_once()